### ISSUE TITLE
how is this different from ts-jest `mocked`?

### ISSUE THREAD

**Issue by rburgst** [lbenie/ts-jest-mock#36]
doesnt the `mocked`  function do the same thing?

https://kulshekhar.github.io/ts-jest/docs/guides/test-helpers/

**Comment by lbenie** [comment]
It does the same thing as far as casting goes.

**Comment by rburgst** [comment]
then I am confused as to why I should use `ts-jest-mock`

**Comment by lbenie** [comment]
If you don't want ts-jest as a dependency.

I do this all the time. Again you're free to use whatever!

ts-jest version does a lot more than just casting stuff for TS though.

If you deem it's better then use it. As far as my needs goes I'll stick with this implementation for my own needs :).


In the end both functions yield the same result.
